"""
This module contains the error code constants throughout the application.
"""

################################################################
# ERROR CODES                                                  #
################################################################

# Non-recoverable error codes
ERR_INPUT_TOO_LONG = 'INPUT_TOO_LONG'
ERR_CANNOT_PARSE_INSTRUCTIONS = 'CANNOT_PARSE_INSTRUCTIONS'
ERR_CANNOT_BUILD_CONTEXT = 'CANNOT_BUILD_CONTEXT'
ERR_TOO_MANY_RETRIES = 'TOO_MANY_RETRIES'

################################################################

# Recoverable error codes
ERR_DUPLICATE_LHS = 'DUPLICATE_LHS'
ERR_NESTED_OPERATOR = 'NESTED_OPERATOR'
ERR_INVALID_OPERATOR = 'INVALID_OPERATOR'
ERR_INVALID_PARAM_COUNT = 'INVALID_PARAM_COUNT'
ERR_INVALID_NODE_TYPE = 'INVALID_NODE_TYPE'
ERR_INVALID_FIELD = 'INVALID_FIELD'
ERR_INVALID_VALUE = 'INVALID_VALUE'
ERR_INVALID_ORDER = 'INVALID_ORDER'
ERR_INVALID_INT = 'INVALID_INT'
ERR_UNDEFINED_NODESET = 'UNDEFINED_NODESET'
ERR_SET_OPERATION_DIFFERENT_TYPES = 'SET_OPERATION_DIFFERENT_TYPES'
ERR_SEVERAL_RETURNS = 'SEVERAL_RETURNS'
ERR_INSTRUCTION_AFTER_RETURN = 'INSTRUCTION_AFTER_RETURN'
ERR_UNUSED_LHS = 'UNUSED_LHS'
ERR_RETURN_WRONG_NODE_TYPE = 'RETURN_WRONG_NODE_TYPE'
