"""
This module provides functions that retrieve and manipulate nodesets from EPFL Graph.
Most of them correspond to the allowed operations in the instructions generated by the LLM.
"""

from app.interfaces.es import es
from app.interfaces.db import db_manager


################################################################
# Auxiliary functions                                          #
################################################################

def drop_duplicates(nodeset):
    unique_nodeset = []
    ids = []
    for node in nodeset:
        if node['NodeKey'] in ids:
            continue

        unique_nodeset.append(node)
        ids.append(node['NodeKey'])

    return unique_nodeset


def get_node_db_info(node_type):
    """
    For a node_type, returns the corresponding (table_name, id_field)
    """

    if node_type == 'Concept':
        return 'Nodes_N_Concept_T_Neighbours', 'id'

    return f'Nodes_N_{node_type}', 'id'


def get_edge_db_info(source_node_type, target_node_type):
    """
    For a combination of (source_node_type, target_node_type),
    returns the corresponding (table_name, source_id_field, target_id_field, order_field)
    """

    if (source_node_type, target_node_type) == ('Course', 'Lecture'):
        return 'Edges_N_Course_N_Lecture_MV', 'from_id', 'to_id', None

    if (source_node_type, target_node_type) == ('Lecture', 'Course'):
        return 'Edges_N_Course_N_Lecture_MV', 'to_id', 'from_id', None

    if (source_node_type, target_node_type) == ('Person', 'Course'):
        return 'Edges_N_Person_N_Course_T_StudyPlanTeacher', 'from_id', 'to_id', None

    if (source_node_type, target_node_type) == ('Course', 'Person'):
        return 'Edges_N_Person_N_Course_T_StudyPlanTeacher', 'to_id', 'from_id', None

    if (source_node_type, target_node_type) == ('Person', 'Lecture'):
        return 'Edges_N_Person_N_Lecture_MV', 'from_id', 'to_id', None

    if (source_node_type, target_node_type) == ('Lecture', 'Person'):
        return 'Edges_N_Person_N_Lecture_MV', 'to_id', 'from_id', None

    if (source_node_type, target_node_type) == ('Person', 'Publication'):
        return 'Edges_N_Person_N_Publication_T_Author', 'from_id', 'to_id', None

    if (source_node_type, target_node_type) == ('Publication', 'Person'):
        return 'Edges_N_Person_N_Publication_T_Author', 'to_id', 'from_id', None

    if (source_node_type, target_node_type) == ('Person', 'Unit'):
        return 'Edges_N_Person_N_Unit_T_Positions', 'from_id', 'to_id', None

    if (source_node_type, target_node_type) == ('Unit', 'Person'):
        return 'Edges_N_Person_N_Unit_T_Positions', 'to_id', 'from_id', None

    return f'Edges_N_{source_node_type}_N_{target_node_type}_T_SemanticSimilarity_CQ', 'from_id', 'to_id', 'score'


def get_key_field(node_type, key):
    key_fields = {
        ('Person', 'Gender'): 'gender_en',
        ('Person', 'Sex'): 'gender_en',
        ('Course', 'ExamType'): 'exam_type',
        ('Course', 'SectionCode'): 'section_code',
        ('Course', 'Section'): 'section_code',
        ('Publication', 'Year'): 'year',
        ('Publication', 'Date'): 'year',
        ('Publication', 'PublicationType'): 'publication_type_en',
        ('Publication', 'Type'): 'publication_type_en',
        ('Publication', 'Journal'): 'published_in',
        ('Publication', 'Conference'): 'published_in',
        ('Lecture', 'Date'): 'creation_date_title',
        ('Lecture', 'Year'): 'creation_date_title',
    }

    return key_fields[node_type, key]


def get_key_value(node_type, key_field, value):
    if isinstance(value, tuple):
        return (
            get_key_value(node_type, key_field, value[0]),
            get_key_value(node_type, key_field, value[1])
        )

    key_values = {
        ('Person', 'gender_en', 'Woman'): 'Female',
        ('Person', 'gender_en', 'Man'): 'Male',
    }

    if (node_type, key_field, value) in key_values:
        return key_values[node_type, key_field, value]

    return value


def want_exact_match(node_type, key_field):
    want_exact_matches = [
        ('Person', 'gender_en'),
        ('Publication', 'year'),
    ]

    return (node_type, key_field) in want_exact_matches


def filter_node_ids(node_type, key, value, filter_ids=None):
    # Build table name and id field
    table_name, id_field = get_node_db_info(node_type)

    # Project implemented (node_type, key) to field name
    key_field = get_key_field(node_type, key)

    # Project implemented (node_type, key_field, value) to field value for enumerations
    key_value = get_key_value(node_type, key_field, value)

    # Filter all nodes table using the (key_field, key_value)
    query = f"""
        SELECT {id_field}
        FROM graphsearch.{table_name}
    """
    query_params = []

    conditions = []
    if filter_ids is not None:
        conditions.append(f"""id IN ({', '.join(['%s'] * len(filter_ids))})""")
        query_params += filter_ids

    if isinstance(value, tuple):
        conditions.append(f"""{key_field} >= %s """)
        conditions.append(f"""{key_field} <= %s """)
        query_params += [key_value[0], key_value[1]]
    elif want_exact_match(node_type, key_field):
        conditions.append(f"""{key_field} = %s """)
        query_params += [key_value]
    else:
        conditions.append(f"""{key_field} LIKE %s """)
        query_params += [f"%{key_value}%"]

    conditions_str = '\nAND '.join(conditions)

    query += f"""WHERE {conditions_str}"""

    if query_params:
        results = db_manager.db.execute_query(query, query_params)
    else:
        results = db_manager.db.execute_query(query)

    node_ids = [str(r) for r, in results]

    return node_ids


################################################################
# Operator functions - Retrieval                               #
################################################################


def search_node(node_type, text):
    """
    Retrieves (from elasticsearch) the node of the given type that better matches the given text.
    Corresponds to the `Search` operator in the instructions.

    Args:
        node_type (str): The type of the node (e.g. `Concept`, `Person`).
        text (str): The piece of text to search for in the node text fields.

    Returns:
        dict: A dictionary with the node `NodeKey`, `NodeType` and `Title`.
    """

    nodeset = es.search_nodes(text, node_type)
    return nodeset[:1]


def get_all_nodes_and_filter(node_type, key, value):
    """
    Retrieves all nodes of the given type filtering by key and value.
    Corresponds to the `All` operator in the instructions.

    Args:
        node_type (str): The type of the node (e.g. `Concept`, `Person`).
        key (str): Either the database field name or some recognised synonym (e.g. `Gender`).
        value (str): Either the database value for the `key` field or some recognised synonym (e.g. `Female`).

    Returns:
        list: A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.
    """

    # Get node ids
    node_ids = filter_node_ids(node_type, key, value)

    # Get nodeset from ids
    nodeset = es.get_nodeset(node_ids, node_type)

    return nodeset


def get_neighborhood(nodeset, node_type, return_order=False):
    """
    Retrieves the neighbours of a nodeset of the given type.
    Corresponds to the `Neighborhood` operator in the instructions.

    Args:
        nodeset (list): A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.
        node_type (str): The type of the node (e.g. `Concept`, `Person`).
        return_order (bool): Whether to return the order of the node in the list of neighbours.

    Returns:
        list: A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.
        If `return_order` is True, the key `Order` is set too.
    """

    if len(nodeset) == 0:
        return []

    # Assuming all nodes in nodeset are of the same type
    source_node_type = nodeset[0]['NodeType']
    target_node_type = node_type

    # Build table name
    db_info = get_edge_db_info(source_node_type, target_node_type)
    table_name, source_id_field, target_id_field, order_field = db_info

    # Extract ids from nodeset
    ids = [node['NodeKey'] for node in nodeset]

    # Build and run query
    query = f"""
        SELECT DISTINCT {target_id_field}
        FROM graphsearch.{table_name}
        WHERE {source_id_field} IN ({', '.join(['%s'] * len(ids))})
    """

    if order_field is not None:
        query += f"""ORDER BY {order_field} DESC"""

    results = db_manager.db.execute_query(query, ids)
    neighbor_ids = [r for r, in results]

    # Remove duplicates while keeping order
    neighbor_ids = list(dict.fromkeys(neighbor_ids))

    # Get nodes from ids
    nodes = es.get_nodeset(neighbor_ids, target_node_type)
    nodes = drop_duplicates(nodes)

    # Return order field if required
    if return_order:
        query = f"""
            SELECT {target_id_field}, MAX({order_field})
            FROM graphsearch.{table_name}
            WHERE {source_id_field} IN ({', '.join(['%s'] * len(ids))})
            AND {target_id_field} IN ({', '.join(['%s'] * len(neighbor_ids))})
            GROUP BY {target_id_field}
        """

        results = db_manager.db.execute_query(query, ids + neighbor_ids)

        for node in nodes:
            node['Order'] = 0
            for node_id, order_value in results:
                if node['NodeKey'] == node_id:
                    node['Order'] = order_value

    return nodes


################################################################
# Operator functions - Manipulation                            #
################################################################


def filter(nodeset, key, value):
    """
    Filters a nodeset according to a field's value or range.
    The key identifier is used to infer which field of the nodes database table is used.
    If no field can be inferred, the value is matched against the Content field on elasticsearch.
    Corresponds to the `Filter` and `FilterRange` operators in the instructions.

    Args:
        nodeset (list): A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.
        key (str): Either the database field name or some recognised synonym (e.g. `Gender`).
        value (str|int|float|tuple): Either the database value (or interval) for the `key` field or some recognised synonym (e.g. `Female`).

    Returns:
        list: A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`. It is always a subset of `nodeset`.
    """

    if len(nodeset) == 0:
        return []

    # Assuming all nodes in nodeset are of the same type
    node_type = nodeset[0]['NodeType']

    # Extract ids from nodeset
    ids = [node['NodeKey'] for node in nodeset]

    try:
        filtered_ids = filter_node_ids(node_type, key, value, filter_ids=ids)
    except Exception as e:
        # If the above does not work as expected, just search both key and value on the Content field in elasticsearch
        nodeset = es.search_node_contents(value, node_type, filter_ids=ids)
        filtered_ids = [node['NodeKey'] for node in nodeset]

    # Filter nodeset, keep only ids found above
    filtered_nodeset = [node for node in nodeset if node['NodeKey'] in filtered_ids]

    return filtered_nodeset


def sort(nodeset, key, order):
    """
    Sorts a nodeset according to a field's value.
    Corresponds to the `Sort` operator in the instructions.

    Args:
        nodeset (list): A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.
        key (str): Either the database field name or some recognised synonym (e.g. `Gender`).
        order (str): Either `ASC` or `DESC` or some recognised synonym.

    Returns:
        list: A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.
        It contains the same nodes as nodeset but rearranged.
    """

    if len(nodeset) == 0:
        return []

    # Assuming all nodes in nodeset are of the same type
    node_type = nodeset[0]['NodeType']

    # Build table name
    table_name, id_field = get_node_db_info(node_type)

    # Extract ids from nodeset
    ids = [node['NodeKey'] for node in nodeset]

    # Project implemented (node_type, key) to field name
    key_field = get_key_field(node_type, key)

    # Project order to database syntax
    if 'DESC' in order or 'Desc' in order or 'desc' in order:
        key_order = 'DESC'
    else:
        key_order = 'ASC'

    # Sort the node ids table using the (key_field, key_value)
    query = f"""
        SELECT {id_field}
        FROM graphsearch.{table_name}
        WHERE {id_field} IN ({', '.join(['%s'] * len(ids))})
        ORDER BY {key_field} {key_order}
    """

    results = db_manager.db.execute_query(query, ids)
    sorted_ids = [str(r) for r, in results]

    # Filter nodeset, keep only ids found above
    filtered_nodeset = [node for node in nodeset if node['NodeKey'] in sorted_ids]

    # Sort nodeset according to returned order
    sorted_nodeset = sorted(filtered_nodeset, key=lambda node: sorted_ids.index(node['NodeKey']))

    return sorted_nodeset


def limit(nodeset, n):
    """
    Returns the first `n` nodes of a nodeset.
    Corresponds to the `Limit` operator in the instructions.

    Args:
        nodeset (list): A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.
        n (int): The maximum number of nodes to return.

    Returns:
        list: A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.
        If nodeset has less than `n` nodes, it returns `nodeset`.
    """

    return nodeset[:n]


################################################################
# Operator functions - Set operations                          #
################################################################


def take_intersection(left_nodeset, right_nodeset):
    """
    Returns the intersection of two nodesets.
    Corresponds to the `Intersection` operator in the instructions.

    Args:
        left_nodeset (list): A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.
        right_nodeset (list): A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.

    Returns:
        list: A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.
        It contains nodes present in both nodesets.
    """

    left_ids = {node['NodeKey'] for node in left_nodeset}
    right_ids = {node['NodeKey'] for node in right_nodeset}

    common_ids = left_ids & right_ids

    common_nodeset = [node for node in left_nodeset + right_nodeset if node['NodeKey'] in common_ids]
    common_nodeset = drop_duplicates(common_nodeset)

    return common_nodeset


def take_union(left_nodeset, right_nodeset):
    """
    Returns the union of two nodesets.
    Corresponds to the `Union` operator in the instructions.

    Args:
        left_nodeset (list): A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.
        right_nodeset (list): A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.

    Returns:
        list: A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.
        It contains nodes present in either of the nodesets.
    """

    union_nodeset = drop_duplicates(left_nodeset + right_nodeset)

    return union_nodeset


def take_difference(left_nodeset, right_nodeset):
    """
    Returns the set difference of two nodesets.
    Corresponds to the `Difference` operator in the instructions.

    Args:
        left_nodeset (list): A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.
        right_nodeset (list): A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.

    Returns:
        list: A list of dictionaries, each representing a node, with the keys `NodeKey`, `NodeType` and `Title`.
        It contains nodes present in the first nodeset which are not in the second nodeset.
    """

    right_ids = {node['NodeKey'] for node in right_nodeset}

    difference_nodeset = [node for node in left_nodeset if node['NodeKey'] not in right_ids]

    return difference_nodeset
